# Generated by Django 4.1.2 on 2022-11-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_conexao_num_conexao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voodinamico",
            name="chegada_real",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="voodinamico",
            name="partida_real",
            field=models.DateTimeField(null=True),
        ),
    ]
