# Generated by Django 4.1.2 on 2022-11-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_alter_voodinamico_chegada_real_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
